name: Library Build and Publish to Nexus

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        type: string

env:
  JAVA_VERSION: '17'
  NEXUS_URL: 'https://nexus.example.com'

jobs:
  build-and-test:
    name: Build and Test Library
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Extract version from tag
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          fi

      - name: Update version in pom.xml
        run: |
          cd library
          mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}

      - name: Build library
        run: |
          cd library
          mvn clean install -DskipTests

      - name: Run tests
        run: |
          cd library
          mvn test

      - name: Run code quality checks
        run: |
          cd library
          mvn checkstyle:check
          mvn pmd:check

      - name: Generate test coverage
        run: |
          cd library
          mvn jacoco:report

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: library/target/surefire-reports/

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: library/target/site/jacoco/

      - name: Build artifacts
        run: |
          cd library
          mvn package -DskipTests

      - name: Upload library artifacts
        uses: actions/upload-artifact@v4
        with:
          name: library-artifacts
          path: |
            library/target/*.jar
            library/target/*.pom

  publish-to-nexus:
    name: Publish to Nexus Repository
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Extract version from tag
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          fi

      - name: Update version in pom.xml
        run: |
          cd library
          mvn versions:set -DnewVersion=${{ steps.get_version.outputs.VERSION }}

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml << EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                        https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>nexus-releases</id>
                <username>\${env.NEXUS_USERNAME}</username>
                <password>\${env.NEXUS_PASSWORD}</password>
              </server>
              <server>
                <id>nexus-snapshots</id>
                <username>\${env.NEXUS_USERNAME}</username>
                <password>\${env.NEXUS_PASSWORD}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Deploy to Nexus
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: |
          cd library
          mvn deploy -DskipTests -DaltDeploymentRepository=nexus-releases::default::${{ env.NEXUS_URL }}/repository/maven-releases/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            library/target/*.jar
          generate_release_notes: true
          draft: false
          prerelease: false

  verify-publication:
    name: Verify Publication
    runs-on: ubuntu-latest
    needs: publish-to-nexus
    
    steps:
      - name: Verify artifact in Nexus
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/v}"
          fi
          
          # Check if artifact is available in Nexus
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -u "${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}" \
            "${{ env.NEXUS_URL }}/repository/maven-releases/com/example/library/${VERSION}/library-${VERSION}.jar")
          
          if [ "$HTTP_CODE" -eq 200 ]; then
            echo "✅ Artifact successfully published to Nexus"
          else
            echo "❌ Artifact not found in Nexus (HTTP $HTTP_CODE)"
            exit 1
          fi

      - name: Notify success
        run: |
          echo "Library version ${{ steps.get_version.outputs.VERSION }} successfully published to Nexus!"
